### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by shazahm1** [Seechay/LIFX-Alexa-Skill#1]
Just wanted to drop by and say thanks! It took a little fumbling along the way since I am not familiar with Alexa Skills and Amazon Lambda but I got it working and it's great. Glancing thru the code and the LIFX HTTP API, this all seems fairly straight forward. I can wait to set some more time aside and see how I can further enhance this.

**Comment by Seechay** [comment]
If you have any suggestions, feel free to drop them by! I'm glad you enjoy it and got it working :)

**Comment by rpcob** [comment]
Hey Seechay,  left you a pm on reddit with some ideas.
