### ISSUE TITLE
[Question] Help with setup

### ISSUE THREAD

**Issue by frakman1** [Seechay/LIFX-Alexa-Skill#3]
Hi there,

Thank you for putting terrific  guide together and sharing it. I would love to get this working but could use your help.

I've followed [this ](https://github.com/alexa/alexa-avs-sample-app/wiki)guide to setup a Raspberry Pi with Alexa Service support. So I already have all the tokens and client ids from AWS working.
I also have a LIFX token for cloud control.

So I went to amazon.developer.com AWS and under 'Alexa' I chose to add a new skill. 
Skill Type =  Custom
Name = lifx
Invocation Name= life ex   (as you recommended)
![image](https://cloud.githubusercontent.com/assets/5826484/22865607/bf9b3fce-f135-11e6-8a4d-68e80c678d9d.png)
![image](https://cloud.githubusercontent.com/assets/5826484/22865609/ca23ff44-f135-11e6-9896-4da67c18c42c.png)

The next page lets you set the Intent Schema and Sample Utterances and Custom Slot type. I copy and pasted the raw text from your files in the speechAssets folder:

![image](https://cloud.githubusercontent.com/assets/5826484/22865587/692f7a9c-f135-11e6-8b18-264b7dd4f5f9.png)

![image](https://cloud.githubusercontent.com/assets/5826484/22865589/6eabd1dc-f135-11e6-822e-1c56893d9a8a.png)

![image](https://cloud.githubusercontent.com/assets/5826484/22865590/7609fde6-f135-11e6-8dc0-f839b890c08b.png)

When I try to save it, I get this error:
![image](https://cloud.githubusercontent.com/assets/5826484/22865596/912058be-f135-11e6-87e3-d905385a5017.png)
Error: There was a problem with your request: Unknown slot type 'LIST_OF_ADJUSTMENTS' for slot 'Adjustment'

Any idea on how to proceed? I am not familiar with all the Amazon jargon so forgive any obvious errors

**Comment by Seechay** [comment]
You're simply adding the slot type incorrectly. For each of the slot types, the first part is what you enter into the box that says "Enter Type" the rest of it is supposed to be separated by new lines. So for all of the additions, you'd have to add 5 custom slots. The | symbol is just used to indicate a new line, similar to the note in the "Enter Values" section itself.

```
LIST_OF_ADJUSTMENTS
dim | lower | decrease | brighten | bright | increase | raise | up | down
```

For example, you'd enter LIST_OF_ADJUSTMENTS in that box and in the "Enter Values" box you must enter each value on a new line.

Enter Type: LIST_OF_ADJUSTMENTS
Enter Values:
dim
lower
decrease
brighten
bright
increase
raise
up
down

**Comment by frakman1** [comment]
I get it now. The custom slots can't all be entered at once and had to be entered one section at a time.
Thank you for explaining that.
I tried it and it works now.
![image](https://cloud.githubusercontent.com/assets/5826484/23096129/53acfc22-f5e4-11e6-9270-acabec834c3e.png)
